service: Self-Help-Service-Portal-backend

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${self:custom.profiles.${opt:stage, 'sandbox2'}}
  region: us-east-1
  environment:
    NODE_ENV: production
    COGNITO_USER_POOL_ID: us-east-1_Rsl2uQOv3
    COGNITO_CLIENT_ID: 2qpfqqak5hm2cljmf8r92s1crf
    DYNAMODB_USERS_TABLE: users

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminGetUser
      Resource: "arn:aws:cognito-idp:us-east-1:572163714811:userpool/us-east-1_Rsl2uQOv3"

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:us-east-1:572163714811:table/users"

custom:
  profiles:
    sandbox: AdministratorAccess-061051226351
    sandbox2: AdministratorAccess-2-572163714811

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /auth/admin/login
          method: post
      - http:
          path: /auth/admin/logout
          method: post
      - http:
          path: /auth/employee/login
          method: post
      - http:
          path: /auth/employee/logout
          method: post
      - http:
          path: /auth/admin/create-employee
          method: post
