service: Self-Help-Service-Portal-backend

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${self:custom.profiles.${opt:stage, 'sandbox2'}}
  region: us-east-1
  environment:
    NODE_ENV: production
    COGNITO_USER_POOL_ID: us-east-1_Rsl2uQOv3
    COGNITO_CLIENT_ID: 2qpfqqak5hm2cljmf8r92s1crf
    DYNAMODB_USERS_TABLE: users
    DYNAMODB_TEAMS_TABLE: Teams
    DYNAMODB_PROJECTS_TABLE: projects
    DYNAMODB_ATTENDANCE_TABLE: Attendance
    DYNAMODB_LEAVE_TABLE: leave_requests

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminGetUser
      Resource: "arn:aws:cognito-idp:us-east-1:572163714811:userpool/us-east-1_Rsl2uQOv3"

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:572163714811:table/users"
        - "arn:aws:dynamodb:us-east-1:572163714811:table/Teams"
        - "arn:aws:dynamodb:us-east-1:572163714811:table/projects"
        - "arn:aws:dynamodb:us-east-1:572163714811:table/Attendance"
        - "arn:aws:dynamodb:us-east-1:572163714811:table/leave_requests"

custom:
  profiles:
    sandbox: AdministratorAccess-061051226351
    sandbox2: AdministratorAccess-2-572163714811

functions:
  app:
    handler: dist/app.handler
    events:
      - http:
          path: /auth/admin/login
          method: post
          cors: true
      - http:
          path: /auth/admin/logout
          method: post
          cors: true
      - http:
          path: /auth/employee/login
          method: post
          cors: true
      - http:
          path: /auth/employee/logout
          method: post
          cors: true
      - http:
          path: /auth/admin/create-employee
          method: post
          cors: true
      - http:
          path: /teams
          method: post
          cors: true
      - http:
          path: /teams
          method: get
          cors: true
      - http:
          path: /teams/{id}
          method: get
          cors: true
      - http:
          path: /teams/{id}
          method: put
          cors: true
      - http:
          path: /teams/{id}
          method: delete
          cors: true
      - http:
          path: /projects
          method: post
          cors: true
      - http:
          path: /projects
          method: get
          cors: true
      - http:
          path: /projects/{id}
          method: get
          cors: true
      - http:
          path: /projects/{id}
          method: put
          cors: true
      - http:
          path: /projects/{id}
          method: delete
          cors: true
      - http:
          path: /attendance/mark
          method: post
          cors: true
      - http:
          path: /attendance/user/{userId}
          method: get
          cors: true
      - http:
          path: /attendance/team/{teamId}/{date}
          method: get
          cors: true
      - http:
          path: /attendance/team/{teamId}/weekly
          method: get
          cors: true
      - http:
          path: /leaves/request
          method: post
          cors: true
      - http:
          path: /leaves
          method: get
          cors: true
      - http:
          path: /leaves/{id}
          method: get
          cors: true
      - http:
          path: /leaves/{id}/approve
          method: put
          cors: true
      - http:
          path: /leaves/{id}/reject
          method: put
          cors: true
      - http:
          path: /leaves/{id}
          method: delete
          cors: true
